name: Tests [PHP7.1-8.5]

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, pcov
          ini-values: post_max_size=256M, log_errors=1
          tools: pecl

      - name: Check PHP Version
        run: php -v

      - name: Clear existing composer
        run: rm -rf vendor composer.lock

      - name: Validate composer.json
        run: composer validate --no-check-lock

      - name: Install dependencies
        run: composer clearcache && composer update --no-cache --prefer-dist

      - name: Run Tests
        env:
          environment_github: true
        run: composer all

      - name: Upload coverage to Codecov
        if: ${{ matrix.php-versions == '8.4' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_COLLECTION }}
          files: ./clover.xml
          fail_ci_if_error: false
